/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Ballpit: typeof import('./src/components/Ballpit.vue')['default']
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    CardNav: typeof import('./src/components/CardNav.vue')['default']
    CircularGugugaga: typeof import('./src/components/CircularGugugaga.vue')['default']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    Particles: typeof import('./src/components/Particles.vue')['default']
    RippleGrid: typeof import('./src/components/RippleGrid.vue')['default']
    RotatingText: typeof import('./src/components/RotatingText.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UmaDashboard: typeof import('./src/components/UmaDashboard.vue')['default']
    UmaDataChart: typeof import('./src/components/UmaDataChart.vue')['default']
  }
}
